version: '3.7'

services:
  jobmanager:
    container_name: jobmanager
    image: flink:1.14.6
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./examples:/examples

  taskmanager:
    image: flink:1.14.6
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 3
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2

  redpanda-1:
    hostname: redpanda-1
    container_name: redpanda-1
    image: docker.vectorized.io/vectorized/redpanda:v23.3.4
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda-1:29092,OUTSIDE://localhost:9092
    - --pandaproxy-addr
    - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
    - --advertise-pandaproxy-addr
    - PLAINTEXT://redpanda-1:28082,OUTSIDE://localhost:8082

    ports:
    - "9092:9092"
    - "9644:9644"